kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    name: auth-app
spec:
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      name: auth-1
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-1
        image: gmoney-auth-image:v0
        command: [ "python", "app.py"]
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: db
              key: db_uri
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask
              key: secret_key
        - name: SECURITY_PASSWORD_SALT
          valueFrom:
            secretKeyRef:
              name: flask
              key: password_salt
---
# Postgres StatefulSet

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: postgres-c
spec:
  selector:
    matchLabels:
      app: postgres-c
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-c
    spec:
      containers:
      - image: postgres:9.6
        name: postgres-c
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-variables
                key: user_username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-variables
                key: user_password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: db-variables
                key: database
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pg-data
      volumes:
        - name: pg-data
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-c
spec:
  type: NodePort
  selector:
    app: postgres-c
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 30008
---